services:
  bot:
    build: .
    restart: on-failure
    stop_signal: SIGINT
    volumes:
      - .:/opt/src
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head; cd src; python main.py"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres